hapi:
  fhir:
    fhir_version: R4
spring:
  datasource:
    platform: postgresql
    url: 'jdbc:postgresql://localhost:5432/hapifhir'
    username: fhiradmin
    password: fhiradmin
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false